# yaml-language-server: $schema=https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/src/main/resources/jsonSchemas/antoraPlaybookSchema.json

runtime:
  cache_dir: ./.cache/antora

site:
  title: reqstool
  url: https://reqstool.github.io
  start_page: reqstool::index.adoc

content:
  sources:
    - url: ./../
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-demo
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-java-annotations
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-java-maven-plugin
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-java-gradle-plugin
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-python-decorators
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-python-poetry-plugin
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-python-hatch-plugin
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-vscode-extension
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-typescript-tags
      branches: HEAD
      start_path: docs
    - url: https://github.com/reqstool/reqstool-ai
      branches: HEAD
      start_path: docs

asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    kroki-server-url: https://kroki.io
    allow-uri-read: true
    sectnumlevels: 4
    toclevels: 3
  extensions:
    - asciidoctor-kroki

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./../supplemental-ui
