# yaml-language-server: $schema=https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/src/main/resources/jsonSchemas/antoraPlaybookSchema.json
# For local development only. Published site: https://reqstool.github.io

runtime:
  cache_dir: ../.cache/antora

site:
  title: Requirements Tool
  url: https://reqstool.github.io
  start_page: reqstool::index.adoc

content:
  sources:
    - url: ~+
      branches: HEAD
      start_path: docs
    - url: ../reqstool-client
      branches: HEAD
      start_path: docs
    - url: ../reqstool-demo
      branches: HEAD
      start_path: docs
    - url: ../reqstool-java-annotations
      branches: HEAD
      start_path: docs
    - url: ../reqstool-java-maven-plugin
      branches: HEAD
      start_path: docs
    - url: ../reqstool-java-gradle-plugin
      branches: HEAD
      start_path: docs
    - url: ../reqstool-python-decorators
      branches: HEAD
      start_path: docs
    - url: ../reqstool-python-poetry-plugin
      branches: HEAD
      start_path: docs
    - url: ../reqstool-python-hatch-plugin
      branches: HEAD
      start_path: docs
    - url: ../reqstool-vscode-extension
      branches: HEAD
      start_path: docs
    - url: ../reqstool-typescript-tags
      branches: HEAD
      start_path: docs
    - url: ../reqstool-ai
      branches: HEAD
      start_path: docs

asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
    allow-uri-read: true
    sectnumlevels: 4
    toclevels: 3
  extensions:
    - asciidoctor-kroki

ui:
  bundle:
    url: ./../.cache/antora/ui-bundle.zip
    snapshot: false
  supplemental_files: ./../supplemental-ui
