name: Publish to GitHub Pages

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    uses: reqstool/.github/.github/workflows/common-publish-to-github-pages.yml@ef815eae0bca7160cdc714126cac73f76d638b39 # 1.0.0
    permissions:
      contents: read
      pages: write
      id-token: write
