name: Publish to GitHub Pages

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    uses: reqstool/.github/.github/workflows/common-publish-to-github-pages.yml@a4203a58cec87861655512b6b277a859db385796 # 1.1.0
    permissions:
      contents: read
      pages: write
      id-token: write
